### PR TITLE
Add dependency to cordova-plugin-webserver

### PR DESCRIPTION
**Pull request by galexandrov**
Remove GCDWebServer.framework and add dependency to cordova-plugin-webserver

### CODE REVIEW

**Comment by tytodorov** [comment]
ping @EddyVerbruggen

**Comment by tytodorov** [comment]
ping @EddyVerbruggen

**Comment by EddyVerbruggen** [comment]
Hi @tytodorov, does this mean AppBuilder now supports loading the new webserver dependency (yesterday it didn't).

**Comment by tytodorov** [comment]
Yes, with this PR you can build an application with WKWebView and Livesync(AppBuilder's 2.10 release) plugins together. We need it to be merged as fast as it could, so we can continue our internal testing for the upcoming 2.10 release of AppBuilder.

**Comment by EddyVerbruggen** [comment]
OK, merged, I will create a release and publish it to the Marketplace as soon as 2.10 is live.

Happy testing!

**Comment by tytodorov** [comment]
Thanks Eddy, could you create and tag the release now and only publish it to the marketplace after the official release of 2.10.

**Comment by EddyVerbruggen** [comment]
doen :+1:

**Pull request merged**
