### PR TITLE
Adding a cache server to access folder with in the apps sandbox

### PR DESCRIPTION
**Pull request by wedgybo**
#### Overview

This is a quick work around to provide access to the apps sandbox of folders.

Normally the cache server can be access via http://localhost:12345. I've only used as a way to fix the issues [imgcache.js](https://github.com/chrisben/imgcache.js) has with using WKWebView.

Here's the simple function I use to translate a file:// url into one served by the cache folder

```js
function convertCacheDest(dest) {
  var found = dest.indexOf('imgcache');
  if (cordova.exec.jsToNativeModes.WK_WEBVIEW_BINDING && dest.indexOf('imgcache')) {
    return 'http://localhost:12345/Documents/' + dest.substring(found);
  }
  return dest;
}
```

You guys have a much better idea of how this should be handled I'm sure but I just wanted to float the idea with you. It's working for my use case with imgcache.js in ionic. Any advise on what to change would be appreciated

#### Related issues 

#22 

#### TODO

There needs to be a few nicer functions exposes to find the location of the cache server. Also having a translation function provided would be nice

Apologies for the mass whitespace removal :)

### CODE REVIEW

**Comment by davidpfahler** [comment]
@wedgybo Thanks! I'm using your fork and it works just fine. It would be great if this makes it to master and next release. I don't know what exactly is needed to progress, but I'm happy to help where I can. I don't know Obj-C, but I do know JavaScript if that helps.

**Comment by EddyVerbruggen** [comment]
Hi @davidpfahler do you have a nice little project which uses this approach which I can review? If not I will create one myself but I thought I'd ask to move things forward a bit quicker.

And @wedgybo thanks!

**Comment by wedgybo** [comment]
No worries guys. Like I say it needs a bit of love as the ports could potentially be different depending on your app. It's unlikely but there should still be a way of exposing the cache location as you can't work it out in javascript land like you can with the www server.

It shouldn't take much to do, but I didn't want to continue if it wasn't the right approach for solving this problem. Starting two servers seems a bit much as it does increase the memory usage quite a bit I noticed. I was wondering if there's another lightweight solution that supports multiple ports and serving different folders from each port. I've not had a chance to look about yet though.

**Comment by etiennea** [comment]
I am interested in this because then it could work with phonegaps new offical plugin https://github.com/phonegap/phonegap-plugin-contentsync so that app's can self update

**Comment by micky2be** [comment]
Wow, looks nice. Thanks

**Comment by nickpastuhov** [comment]
Nice fork.
Works like a charm!

**Comment by EddyVerbruggen** [comment]
Hey guys, I've been trying coming up with a way to do the same without managing an additional webserver, and also make it transparent to the developer (no need to load those cached files from a different webserver/port).

It would be awesome if some of you can try the updated version (available as 0.3.8-dev in the master branch) and let me know if you yield the same results as the cache server proposed in this issue.
I tested it a little already with the [phonegap-content-sync plugin](https://github.com/phonegap/phonegap-plugin-contentsync) and the [imgcache.js](https://github.com/chrisben/imgcache.js) library.

Thx,
Eddy

**Comment by nickpastuhov** [comment]
Eddy,

Should we use your approach in the same way as the wedgybo's approach? I.e. http://localhost:12345/Library/NoCloud/...

**Comment by EddyVerbruggen** [comment]
@nickpastuhov good Q. I'm aiming at making this a drop-in solution for the developer, so you should be able to use it in the same way as you did with the default webview.

In imgcache.js's case this means you should simply be able to drop that library in.

And the 'phonegap content sync' plugin seems to store files in `/var/.../Data/.../Library/<myalias>` which can simply be used like `/<myfile.gif>"/>`

Hope that makes sense && works.

**Comment by rbabayoff** [comment]
Question regarding this pr (not using content sync):

http;//localhost:12344/ is being served from my app's bundle container/www

If I need to serve files from Library/NoCloud folder in data container (i.e. cordova.file.dataDirectory), what is the http path to that?

**Comment by wedgybo** [comment]
It should be `http://localhost:12345/Library/NoCloud`

**Comment by EddyVerbruggen** [comment]
@rbabayoff It depends: if you've used the fork of @wedgybo it's what he said.

But if you use the master branch of this repo you should be able to pass in the full path. E.g. when using it with an image: ``.

If the latter works, we could also come up with a way to use just `` if that is more convenient. But that's not currently supported.

**Comment by rbabayoff** [comment]
Thanks, will check it out. Are you guys implementing this using multiple calls to addGETHandlerForPath for the different possible folders so that only one web server serves all possible paths?

**Comment by EddyVerbruggen** [comment]
@rbabayoff That is indeed the approach I'm trying to implement, but with a slightly [different method](https://github.com/Telerik-Verified-Plugins/WKWebView/blob/master/src/ios/AppDelegate%2BWKWebViewPolyfill.m#L51).

This needs to be polished a bit, but I need to first know if this approach works for you.

**Comment by rbabayoff** [comment]
I'll check it today. Is there a problem with using multiple addGETHandlerForPath handlers?

**Comment by rbabayoff** [comment]
@EddyVerbruggen, this will not work, at least not for me, since, for some reason, every time I run the app again from xcode on my device or in the simulator, the app ID (or whatever id it is) in the path changes (i.e. the one in /Containers/Data/Application/<ID>/Documents ), which means that if your app saves the absolute path to a file and then tries to use it to access the file in a future run, the path won't work, since the id changed. I recommend coming up with a solution where you map the app folders to the actual file system folders, i.e. map:

/Documents
/Library
/tmp

**Comment by tuomaslaa** [comment]
@rbabayoff is right. The Application ID changes. 

Any progress? 

Vote for

**Comment by EddyVerbruggen** [comment]
Will look at it shortly!

**Comment by EddyVerbruggen** [comment]
Hi @tuomaslaa and @rbabayoff you can now (v 0.3.8) use '/Library/..' and '/Documents/..' as you suggested. Great enhancement!

**Comment by rbabayoff** [comment]
Perfect, thanks!

**Comment by tuomaslaa** [comment]
Works like a charm! Thank you for the good work.

**Comment by EddyVerbruggen** [comment]
Awesome, thanks for testing this so quickly!

**Pull request merged**
